### ISSUE TITLE
vue-18n 开发环境告警

### ISSUE THREAD

**Issue by YutHelloWorld** [nekobc1998923/vitecamp#10]
vue-i18n.esm-bundler.js:46 You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.

升级vue-v18n到v9.1.10可以解决

**Comment by nekobc1998923** [comment]
vue-v18n 有告警吗？我在开发环境下没有看到输出告警提示；
