### ISSUE TITLE
dev的时候报错，请问这是什么问题

### ISSUE THREAD

**Issue by baoguiguo** [nekobc1998923/vitecamp#11]
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/56422432/177129640-3274ed46-31a6-464c-bd61-38e772205100.png">

**Comment by nekobc1998923** [comment]
![7343784e92b14c9caac44a035155bf69](https://user-images.githubusercontent.com/46434433/177132561-d7477d93-31fb-468b-8983-522fac3d868e.png)
是不是没有安装 vueuse？

**Comment by ydongabc** [comment]
node版本v14.1.0，也一样出现这个问题

**Comment by nekobc1998923** [comment]
这个问题就是 @vueuse 没有安装成功呀。你们重新install就好了呀
