### ISSUE TITLE
希望引入文件路由与布局系统

### ISSUE THREAD

**Issue by only52607** [nekobc1998923/vitecamp#17]
文件路由可参考

[vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages)

[unplugin-vue-router](https://github.com/posva/unplugin-vue-router)

布局系统可参考

[vite-plugin-vue-layouts](https://github.com/JohnCampionJr/vite-plugin-vue-layouts)

[vite-plugin-vue-meta-layouts](https://github.com/dishait/vite-plugin-vue-meta-layouts)

**Comment by nekobc1998923** [comment]
没有加因为：我觉得文件路由不利于做更精细的页面鉴权和meta功能拓展
