### ISSUE TITLE
拉下代码，直接运行build 会有eslint的报错

### ISSUE THREAD

**Issue by kevinlvhsl** [nekobc1998923/vitecamp#2]
建议多写点页面， 再反复打磨lint版本配置

**Comment by nekobc1998923** [comment]
我这边新拉了一份，安装完依赖一切正常，你 install 依赖了吗

**Comment by nekobc1998923** [comment]
可以截个图看下 eslint 有什么问题

**Comment by urechoes** [comment]
![image](https://user-images.githubusercontent.com/22517252/160859119-1920564b-62b4-4513-bb2b-5d64c71cf8cd.png)
我来补图，遇到了同样的问题

**Comment by nekobc1998923** [comment]
上图的问题是打包的时候， vue-tsc --noEmit 检测到 node_modules 里面有的包，它们的类型有错误；我已经修复了一版，可以再试下
