### ISSUE TITLE
npm run dev　报错

### ISSUE THREAD

**Issue by n3e97** [nekobc1998923/vitecamp#3]
![image](https://user-images.githubusercontent.com/15063509/157839666-38b103f2-e1a7-4a6f-ba46-2aa4a6c9c0f8.png)
是组件问题吗，npm ｉ是成功的

**Comment by n3e97** [comment]
![image](https://user-images.githubusercontent.com/15063509/157840519-8847a125-3e36-4810-ac8e-f41c8cbd1048.png)

**Comment by nekobc1998923** [comment]
请问你拉的是最新的代码吗？我之前的一次提交中，把 vite-plugin-checker 插件移除了

**Comment by nekobc1998923** [comment]
![image](https://user-images.githubusercontent.com/46434433/157841829-9eb75571-f065-4ea2-9a08-cae34dde40ca.png)
我拉了一下你fork的仓库，跑起来是正常的，你这个截图我看不出问题是什么.....

**Comment by n3e97** [comment]
![image](https://user-images.githubusercontent.com/15063509/158089211-debab0f7-36ec-4bc6-ba52-712cf1ff07e0.png)
这个日志能看出上面吗，我是downloadzip你的库的代码的，很奇怪

**Comment by nekobc1998923** [comment]
说实话...看不出来

**Comment by nekobc1998923** [comment]
更新 vite 到2.9.0，顺便适配修改了一点 build 打包的问题；如果有时间的话可以再试下是否还有上图问题~

**Comment by laoer536** [comment]
现在能够正常跑起来
