### ISSUE TITLE
vite.config.json 打包读取环境变量错误

### ISSUE THREAD

**Issue by ForeverSun** [nekobc1998923/vitecamp#7]
![image](https://user-images.githubusercontent.com/10215382/169284441-a800a5f4-d347-4937-bf94-a108e8ac2e1d.png)
改为
![image](https://user-images.githubusercontent.com/10215382/169284619-dea39068-4e17-437b-98bf-514fb745173d.png)

**Comment by nekobc1998923** [comment]
fixed thanks!
